server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 365d;
        add_header Cache-Control "public, immutable";
    }
    location = /service-worker.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
